apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app : mychatapp
  template:
    metadata:
      name: chatapp-pod
      labels:
        app: mychatapp
    spec:
      containers:
        - name: chatapp-container
          image: gopal1409/chatapp
          ports:
            - containerPort: 8080
      